Contains exercises about digits
ChriSangHoon/RUST_practice pull request #4
Opened 2022-08-04 08:26 UTC by ChriSangHoon

Five digits exercises from LeetCode

2022-08-04 20:34 UTC, msk requested changes
PR을 올릴 때에는 conflict가 없는지 꼭 확인하세요. 가장 좋은 습관은 브랜치를 push하기 이전에 다음과 같이 rebase를 하는 겁니다.

```sh
git fetch origin
git rebase origin/master
```

2022-08-05 00:42 UTC, ChriSangHoon commented
master의 exer1.rs 파일의 충돌이 있어서 해결한 뒤에 새로 요청드립니다. slack에 올려주신 자료로 더 공부하면서 충돌과 관련하여 주의하겠습니다.!

2022-08-05 00:53 UTC, msk commented
> master의 exer1.rs 파일의 충돌이 있어서 해결한 뒤에 새로 요청드립니다.

아직 conflict가 있다고 나오는데요. 머지하는 버튼 바로 위에 보면 "This branch cannot be rebased due to conflicts"라고 나와있습니다.

충돌을 어떻게 해결하셨나요? git rebase origin/master 후에 push하신 건가요?

2022-08-05 01:34 UTC, ChriSangHoon commented
어제 push 전에 git rebase origin/master 이후에 push를 진행했었는데, conflict가 있다고 해주셔서 git pull origin master를 해보니 exer1.rs 파일에 unmerged path 에러가 보여서 git add를 사용했습니다. 현재는 git status에 충돌된 내용이 보이지 않고 제 github에도 아래 사진과 같이 보이는데 혹시 시간 괜찮으실때 확인 한 번 부탁드려도 될까요?

<img width="879" alt="image" src="https://user-images.githubusercontent.com/88368300/182982393-5dd21f1f-d9cd-43eb-8865-85b14168ffef.png">

2022-08-05 02:03 UTC, msk requested changes

2022-08-05 02:03 UTC, msk commented on leet_code/exer9.rs
> +    for i in 0..str.len() {
`str.chars()`를 쓰세요.

2022-08-05 04:01 UTC, msk approved these changes

2022-08-05 04:01 UTC, merged